package eci.cosw.eps.model;
// Generated Feb 18, 2012 10:07:45 PM by Hibernate Tools 3.4.0.CR1


import java.text.DateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppointmentId generated by hbm2java
 */
@Embeddable
public class AppointmentId  implements java.io.Serializable {

	private Date date;
     private int afiliateId;

    public AppointmentId() {
    }

    public AppointmentId(Date date, int afiliateId) {
       this.date = date;
       this.afiliateId = afiliateId;
    }
   


    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


    @Column(name="afiliate_id", nullable=false)
    public int getAfiliateId() {
        return this.afiliateId;
    }
    
    public void setAfiliateId(int afiliateId) {
        this.afiliateId = afiliateId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppointmentId) ) return false;
		 AppointmentId castOther = ( AppointmentId ) other; 
         
		 return ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) )
 && (this.getAfiliateId()==castOther.getAfiliateId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         result = 37 * result + this.getAfiliateId();
         return result;
   }   

   @Override
   public String toString() {
	return this.date.toString();
}

}


