package eci.cosw.eps.model;
// Generated Feb 18, 2012 10:07:45 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name="BILLS"
    , uniqueConstraints = @UniqueConstraint(columnNames="aprobation_code") 
)
public class Bill  implements java.io.Serializable {

	 private Integer id;
     private Ips ips;
     private int value;
     private String aprobationCode;

    public Bill() {
    }

    public Bill(int id, Ips ips, int value, String aprobationCode) {
       this.id = id;	
       this.ips = ips;
       this.value = value;
       this.aprobationCode = aprobationCode;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ips_id", nullable=false)
    public Ips getIps() {
        return this.ips;
    }
    
    public void setIps(Ips ips) {
        this.ips = ips;
    }

    
    @Column(name="value", nullable=false)
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }

    
    @Column(name="aprobation_code", unique=false, nullable=true, length=45)
    public String getAprobationCode() {
        return this.aprobationCode;
    }
    
    public void setAprobationCode(String aprobationCode) {
        this.aprobationCode = aprobationCode;
    }




}


