
package eci.cosw.eps.integration.fosyga;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServicesException", targetNamespace = "http://services.persistencia.eci.edu/")
public class ServicesException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServicesException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServicesException_Exception(String message, ServicesException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServicesException_Exception(String message, ServicesException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eci.cosw.eps.integration.fosyga.ServicesException
     */
    public ServicesException getFaultInfo() {
        return faultInfo;
    }

}
