
package eci.cosw.eps.integration.fosyga;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicesEps", targetNamespace = "http://services.persistencia.eci.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicesEps {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ServicesException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "registrarSolicitudPago", targetNamespace = "http://services.persistencia.eci.edu/", className = "eci.cosw.eps.integration.fosyga.RegistrarSolicitudPago")
    @ResponseWrapper(localName = "registrarSolicitudPagoResponse", targetNamespace = "http://services.persistencia.eci.edu/", className = "eci.cosw.eps.integration.fosyga.RegistrarSolicitudPagoResponse")
    public void registrarSolicitudPago(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3)
        throws ServicesException_Exception
    ;

}
