
package eci.cosw.eps.integration.ips;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServicesService", targetNamespace = "http://services.b8.cosw.eci.edu.co/")
public class WebServicesService
    extends Service
{

    private final static URL WEBSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESSERVICE_EXCEPTION;
    private final static QName WEBSERVICESSERVICE_QNAME = new QName("http://services.b8.cosw.eci.edu.co/", "WebServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            URL baseUrl;
            baseUrl = WebServicesService.class.getResource(".");
            URL u=WebServicesService.class.getResource("WebServices.xml");
            url = new URL(baseUrl, u.toString());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESSERVICE_WSDL_LOCATION = url;
        WEBSERVICESSERVICE_EXCEPTION = e;
    }

    public WebServicesService() {
        super(__getWsdlLocation(), WEBSERVICESSERVICE_QNAME);
    }

    public WebServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESSERVICE_QNAME);
    }

    public WebServicesService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESSERVICE_QNAME);
    }

    public WebServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESSERVICE_QNAME);
    }

    public WebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort() {
        return super.getPort(new QName("http://services.b8.cosw.eci.edu.co/", "WebServicesPort"), WebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.b8.cosw.eci.edu.co/", "WebServicesPort"), WebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESSERVICE_EXCEPTION!= null) {
            throw WEBSERVICESSERVICE_EXCEPTION;
        }
        return WEBSERVICESSERVICE_WSDL_LOCATION;
    }

}
