
package eci.cosw.eps.integration.ips;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WebServicesException", targetNamespace = "http://services.b8.cosw.eci.edu.co/")
public class WebServicesException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WebServicesException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WebServicesException_Exception(String message, WebServicesException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WebServicesException_Exception(String message, WebServicesException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eci.cosw.eps.integration.ips.WebServicesException
     */
    public WebServicesException getFaultInfo() {
        return faultInfo;
    }

}
