
package eci.cosw.eps.integration.ips;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://services.b8.cosw.eci.edu.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "appointmentDetails", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.AppointmentDetails")
    @ResponseWrapper(localName = "appointmentDetailsResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.AppointmentDetailsResponse")
    public String appointmentDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerAppointment", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.RegisterAppointment")
    @ResponseWrapper(localName = "registerAppointmentResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.RegisterAppointmentResponse")
    public String registerAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "cancelAppointment", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.CancelAppointment")
    @ResponseWrapper(localName = "cancelAppointmentResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.CancelAppointmentResponse")
    public void cancelAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "carryOutAppointment", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.CarryOutAppointment")
    @ResponseWrapper(localName = "carryOutAppointmentResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.CarryOutAppointmentResponse")
    public void carryOutAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "showUpAppointment", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.ShowUpAppointment")
    @ResponseWrapper(localName = "showUpAppointmentResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.ShowUpAppointmentResponse")
    public void showUpAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "todayScheduleDetails", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.TodayScheduleDetails")
    @ResponseWrapper(localName = "todayScheduleDetailsResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.TodayScheduleDetailsResponse")
    public List<String> todayScheduleDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "availableSchedule", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.AvailableSchedule")
    @ResponseWrapper(localName = "availableScheduleResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.AvailableScheduleResponse")
    public List<String> availableSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enumerateSpecialists", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.EnumerateSpecialists")
    @ResponseWrapper(localName = "enumerateSpecialistsResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.EnumerateSpecialistsResponse")
    public List<String> enumerateSpecialists()
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "patientDetails", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.PatientDetails")
    @ResponseWrapper(localName = "patientDetailsResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.PatientDetailsResponse")
    public String patientDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateMedicalHistory", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.UpdateMedicalHistory")
    @ResponseWrapper(localName = "updateMedicalHistoryResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.UpdateMedicalHistoryResponse")
    public void updateMedicalHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9)
        throws WebServicesException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws WebServicesException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dueBills", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.DueBills")
    @ResponseWrapper(localName = "dueBillsResponse", targetNamespace = "http://services.b8.cosw.eci.edu.co/", className = "eci.cosw.eps.integration.ips.DueBillsResponse")
    public List<String> dueBills(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws WebServicesException_Exception
    ;

}
